create extension if not exists pgcrypto;

create table if not exists public.ingredients (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  aliases jsonb default '[]'::jsonb,
  category text,
  common_dose_min numeric,
  common_dose_max numeric,
  unit text,
  default_dose numeric,
  gummy_suitability text,
  taste_risk text,
  heat_sensitivity text,
  oil_soluble boolean default false,
  mineral_heavy boolean default false,
  requires_rd_review boolean default false,
  regulatory_review_required boolean default false,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.ingredients
  add column if not exists id uuid default gen_random_uuid(),
  add column if not exists name text,
  add column if not exists aliases jsonb default '[]'::jsonb,
  add column if not exists category text,
  add column if not exists common_dose_min numeric,
  add column if not exists common_dose_max numeric,
  add column if not exists unit text,
  add column if not exists default_dose numeric,
  add column if not exists gummy_suitability text,
  add column if not exists taste_risk text,
  add column if not exists heat_sensitivity text,
  add column if not exists oil_soluble boolean default false,
  add column if not exists mineral_heavy boolean default false,
  add column if not exists requires_rd_review boolean default false,
  add column if not exists regulatory_review_required boolean default false,
  add column if not exists notes text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.ingredients
  alter column id set default gen_random_uuid(),
  alter column name set not null,
  alter column aliases set default '[]'::jsonb,
  alter column oil_soluble set default false,
  alter column mineral_heavy set default false,
  alter column requires_rd_review set default false,
  alter column regulatory_review_required set default false,
  alter column created_at set default now(),
  alter column updated_at set default now();

create unique index if not exists ingredients_name_key
  on public.ingredients (name);

grant select, insert on public.ingredients to anon, authenticated;
grant update (aliases, category, common_dose_min, common_dose_max, unit, default_dose, gummy_suitability, taste_risk, heat_sensitivity, oil_soluble, mineral_heavy, requires_rd_review, regulatory_review_required, notes, updated_at)
  on public.ingredients to anon, authenticated;

grant select, insert on public.ingredient_prices to anon, authenticated;
grant update (price_per_kg_usd, price_confidence, last_updated, notes)
  on public.ingredient_prices to anon, authenticated;

insert into public.ingredients (
  name, aliases, category, common_dose_min, common_dose_max, unit,
  default_dose, gummy_suitability, taste_risk, heat_sensitivity,
  oil_soluble, mineral_heavy, requires_rd_review, regulatory_review_required, notes
)
values
  ('Melatonin', '[]'::jsonb, 'Sleep / Calm', 1, 10, 'mg', 3, 'high', 'low', 'medium', false, false, false, false, 'Common sleep support active. Verify serving size and target market.'),
  ('L-Theanine', '["Theanine"]'::jsonb, 'Sleep / Calm', 50, 200, 'mg', 100, 'high', 'low', 'low', false, false, false, false, 'Generally suitable for gummies. Mild taste profile.'),
  ('GABA', '["Gamma-Aminobutyric Acid"]'::jsonb, 'Sleep / Calm', 50, 250, 'mg', 100, 'medium', 'medium', 'low', false, false, false, false, 'Bitter taste may require flavor masking at higher use levels.'),
  ('Chamomile Extract', '["Chamomile"]'::jsonb, 'Sleep / Calm', 25, 250, 'mg', 100, 'medium', 'medium', 'medium', false, false, false, false, 'Botanical extract ratio and allergen considerations should be reviewed.'),
  ('Lemon Balm Extract', '["Lemon Balm"]'::jsonb, 'Sleep / Calm', 100, 500, 'mg', 250, 'medium', 'medium', 'medium', false, false, false, false, 'Verify extract ratio and marker compounds if applicable.'),
  ('Passionflower Extract', '["Passionflower"]'::jsonb, 'Sleep / Calm', 50, 250, 'mg', 100, 'medium', 'medium', 'medium', false, false, false, false, 'Botanical taste may require flavor masking.'),
  ('Valerian Root Extract', '["Valerian Root","Valerian"]'::jsonb, 'Sleep / Calm', 100, 500, 'mg', 250, 'low', 'high', 'medium', false, false, true, false, 'Strong odor and taste. Requires formulation review.'),
  ('Magnesium L-Threonate', '["Magtein"]'::jsonb, 'Sleep / Calm', 500, 2000, 'mg', 1000, 'medium', 'medium', 'low', false, true, true, false, 'Use elemental magnesium basis where applicable. Mineral and pectin interaction review recommended.'),
  ('Ashwagandha Extract', '["Ashwagandha","Withania Somnifera"]'::jsonb, 'Stress / Mood', 125, 600, 'mg', 300, 'medium', 'high', 'medium', false, false, true, false, 'Earthy taste and standardization should be reviewed.'),
  ('5-HTP', '["5-Hydroxytryptophan"]'::jsonb, 'Stress / Mood', 25, 100, 'mg', 50, 'medium', 'medium', 'medium', false, false, true, false, 'Regulatory, warning language, and stability review recommended.'),
  ('Rhodiola Rosea Extract', '["Rhodiola"]'::jsonb, 'Stress / Mood', 100, 400, 'mg', 200, 'medium', 'medium', 'medium', false, false, true, false, 'Verify rosavins and salidroside standardization.'),
  ('Saffron Extract', '["Saffron"]'::jsonb, 'Stress / Mood', 15, 30, 'mg', 28, 'medium', 'medium', 'medium', false, false, true, false, 'Color and botanical standardization should be reviewed.'),
  ('Caffeine', '["Natural Caffeine"]'::jsonb, 'Energy / Focus', 25, 200, 'mg', 50, 'medium', 'high', 'low', false, false, true, false, 'Bitter active. Serving limits, warnings, and flavor masking required.'),
  ('L-Tyrosine', '["Tyrosine"]'::jsonb, 'Energy / Focus', 500, 2000, 'mg', 500, 'medium', 'medium', 'medium', false, false, true, false, 'Amino acid with moderate active load. Serving size and flavor impact should be reviewed.'),
  ('Green Tea Extract', '["EGCG","Camellia Sinensis"]'::jsonb, 'Energy / Focus', 100, 500, 'mg', 250, 'medium', 'high', 'medium', false, false, true, false, 'Bitter/astringent taste. EGCG and caffeine levels should be verified.'),
  ('Guarana Extract', '["Guarana"]'::jsonb, 'Energy / Focus', 50, 250, 'mg', 100, 'medium', 'high', 'medium', false, false, true, false, 'Contains caffeine. Requires label and warning review.'),
  ('Ginseng Extract', '["Panax Ginseng","Ginseng"]'::jsonb, 'Energy / Focus', 100, 400, 'mg', 200, 'medium', 'medium', 'medium', false, false, true, false, 'Botanical standardization and taste should be reviewed.'),
  ('Lion''s Mane Mushroom', '["Lion''s Mane","Hericium Erinaceus"]'::jsonb, 'Nootropic', 250, 1000, 'mg', 500, 'medium', 'medium', 'medium', false, false, true, false, 'High dose may require multiple gummies. Verify extract ratio.'),
  ('Alpha GPC', '["Alpha-GPC"]'::jsonb, 'Nootropic', 100, 600, 'mg', 300, 'medium', 'medium', 'medium', false, false, true, false, 'Hygroscopic behavior and taste should be evaluated.'),
  ('Citicoline', '["CDP Choline"]'::jsonb, 'Nootropic', 100, 500, 'mg', 250, 'medium', 'medium', 'medium', false, false, true, false, 'Review dose, taste, and regulatory positioning.'),
  ('Bacopa Monnieri Extract', '["Bacopa"]'::jsonb, 'Nootropic', 150, 450, 'mg', 300, 'medium', 'high', 'medium', false, false, true, false, 'Bitter botanical. Verify bacoside standardization.'),
  ('Creatine Monohydrate', '["Creatine"]'::jsonb, 'Sports', 1000, 5000, 'mg', 1000, 'medium', 'medium', 'medium', false, false, true, false, 'High-dose active. Serving size often needs multiple gummies.'),
  ('BCAA', '["Branched-Chain Amino Acids"]'::jsonb, 'Sports', 1000, 5000, 'mg', 2000, 'low', 'high', 'medium', false, false, true, false, 'Very high dose and bitter taste. Technical review required.'),
  ('Beta-Alanine', '[]'::jsonb, 'Sports', 1600, 3200, 'mg', 1600, 'low', 'medium', 'medium', false, false, true, false, 'High-dose sports active. Serving size will likely require multiple gummies.'),
  ('Citrulline Malate', '["L-Citrulline"]'::jsonb, 'Sports', 1000, 6000, 'mg', 1000, 'low', 'medium', 'medium', false, false, true, false, 'Very high active load for gummies. Technical review and multi-gummy serving likely required.'),
  ('L-Carnitine', '["Carnitine"]'::jsonb, 'Sports', 250, 1500, 'mg', 500, 'medium', 'medium', 'medium', false, false, true, false, 'Dose and taste may require flavor masking.'),
  ('Electrolyte Blend', '["Electrolytes"]'::jsonb, 'Sports', 100, 1000, 'mg', 300, 'medium', 'high', 'low', false, true, true, false, 'Mineral salts may affect taste, pectin, and texture.'),
  ('Collagen Peptides', '["Collagen"]'::jsonb, 'Beauty', 500, 5000, 'mg', 1000, 'low', 'medium', 'medium', false, false, true, false, 'High dose active. May require multiple gummies or alternate format.'),
  ('Hyaluronic Acid', '["Sodium Hyaluronate"]'::jsonb, 'Beauty', 50, 200, 'mg', 100, 'medium', 'low', 'medium', false, false, false, false, 'Review molecular weight and supplier specification.'),
  ('Biotin', '["Vitamin B7"]'::jsonb, 'Beauty', 30, 5000, 'mcg', 2500, 'high', 'low', 'medium', false, false, false, false, 'Micro-dose vitamin. Verify label claim and overage.'),
  ('Keratin', '[]'::jsonb, 'Beauty', 250, 500, 'mg', 250, 'medium', 'medium', 'medium', false, false, true, false, 'Protein-derived active. Source, allergen status, and taste should be reviewed.'),
  ('Bamboo Extract', '["Bambusa Vulgaris","Bambusa Vulgaris / Bamboo Extract"]'::jsonb, 'Beauty / Joint / Mineral Support', 100, 500, 'mg', 250, 'medium', 'medium', 'low', false, false, false, false, 'Often standardized for silica. Verify extract ratio and silica content.'),
  ('Lutein', '[]'::jsonb, 'Eye Health', 5, 20, 'mg', 10, 'medium', 'low', 'medium', true, false, true, false, 'Oil-soluble carotenoid. May require dispersion system.'),
  ('Zeaxanthin', '[]'::jsonb, 'Eye Health', 1, 10, 'mg', 2, 'medium', 'low', 'medium', true, false, true, false, 'Oil-soluble carotenoid. Review dispersion and color impact.'),
  ('Beta Carotene', '[]'::jsonb, 'Vitamin / Eye Health', 1, 6, 'mg', 3, 'medium', 'low', 'medium', true, false, true, false, 'Oil-soluble carotenoid. May require dispersion system.'),
  ('Vitamin C', '["Ascorbic Acid"]'::jsonb, 'Immune', 60, 500, 'mg', 100, 'high', 'medium', 'medium', false, false, false, false, 'Acidic taste can support fruit profiles but may affect pH.'),
  ('Elderberry Extract', '["Elderberry"]'::jsonb, 'Immune', 50, 300, 'mg', 100, 'medium', 'medium', 'medium', false, false, false, false, 'Can contribute dark color and berry flavor notes.'),
  ('Echinacea Extract', '["Echinacea"]'::jsonb, 'Immune', 100, 500, 'mg', 250, 'medium', 'medium', 'medium', false, false, true, false, 'Botanical extract ratio and taste should be reviewed.'),
  ('Quercetin', '[]'::jsonb, 'Immune', 100, 500, 'mg', 250, 'medium', 'high', 'medium', false, false, true, false, 'Bitter and colored active. May need flavor masking.'),
  ('Probiotics', '["Probiotic"]'::jsonb, 'Digestive', 1, 10, 'billion CFU', 2, 'low', 'low', 'high', false, false, true, false, 'CFU should not be counted as mg active load. Heat stability and overage required.'),
  ('Prebiotic Fiber', '["Inulin","FOS","Fructooligosaccharides"]'::jsonb, 'Digestive', 500, 3000, 'mg', 1000, 'medium', 'low', 'low', false, false, true, false, 'High dose can affect texture and water activity.'),
  ('Apple Cider Vinegar', '["ACV"]'::jsonb, 'Digestive', 250, 1000, 'mg', 500, 'medium', 'high', 'low', false, false, true, false, 'Strong acidic taste and odor. Requires flavor review.'),
  ('Ginger Root Extract', '["Ginger"]'::jsonb, 'Digestive', 50, 500, 'mg', 100, 'medium', 'medium', 'medium', false, false, false, false, 'Spicy taste can be useful in some flavor systems.'),
  ('Peppermint Leaf Extract', '["Peppermint"]'::jsonb, 'Digestive', 50, 250, 'mg', 100, 'medium', 'medium', 'medium', false, false, false, false, 'Botanical extract with strong flavor contribution. Verify extract ratio.'),
  ('CoQ10', '["Coenzyme Q10","Ubiquinone"]'::jsonb, 'Heart / Metabolic', 30, 200, 'mg', 100, 'medium', 'medium', 'medium', true, false, true, false, 'Oil-soluble active. Dispersion and color should be reviewed.'),
  ('Algae-based Omega-3 DHA', '["DHA","Algae DHA","Omega-3 DHA"]'::jsonb, 'Heart / Brain / Eye Health', 100, 500, 'mg', 250, 'low', 'high', 'high', true, false, true, false, 'Oil-soluble, oxidation and off-taste risk. May need emulsification.'),
  ('Berberine', '[]'::jsonb, 'Heart / Metabolic', 250, 1000, 'mg', 500, 'low', 'high', 'medium', false, false, true, false, 'Very bitter active and high dose. Technical review required.'),
  ('Chromium Picolinate', '["Chromium"]'::jsonb, 'Heart / Metabolic', 35, 200, 'mcg', 120, 'medium', 'medium', 'low', false, true, true, false, 'Use elemental chromium basis. Mineral review recommended.'),
  ('Resveratrol', '[]'::jsonb, 'Heart / Metabolic', 50, 250, 'mg', 100, 'medium', 'medium', 'medium', false, false, true, false, 'Botanical polyphenol. Color, taste, and stability review recommended.'),
  ('Turmeric Root Extract 4:1', '["Turmeric","Curcumin"]'::jsonb, 'Joint / Inflammation Support', 250, 1000, 'mg', 500, 'medium', 'high', 'medium', false, false, true, false, 'Strong taste/color. Verify curcuminoid standardization if applicable.'),
  ('Glucosamine Sulfate', '["Glucosamine"]'::jsonb, 'Joint', 500, 1500, 'mg', 750, 'low', 'medium', 'medium', false, false, true, false, 'High dose and potential shellfish allergen review required.'),
  ('Chondroitin Sulfate', '["Chondroitin"]'::jsonb, 'Joint', 400, 1200, 'mg', 400, 'low', 'medium', 'medium', false, false, true, false, 'High dose and animal source documentation should be reviewed.'),
  ('MSM', '["Methylsulfonylmethane"]'::jsonb, 'Joint', 500, 2000, 'mg', 1000, 'low', 'high', 'medium', false, false, true, false, 'Sulfur taste and high load require formulation review.'),
  ('Calcium', '["Calcium Citrate","Calcium Carbonate"]'::jsonb, 'Minerals', 100, 500, 'mg', 250, 'medium', 'medium', 'low', false, true, true, false, 'Use elemental calcium basis. Pectin interaction risk.'),
  ('Magnesium Glycinate', '["Magnesium"]'::jsonb, 'Minerals', 50, 200, 'mg', 100, 'medium', 'high', 'low', false, true, true, false, 'Use elemental magnesium basis. Mineral/pectin interaction risk.'),
  ('Zinc Citrate', '["Zinc"]'::jsonb, 'Mineral / Immune', 5, 15, 'mg', 10, 'medium', 'high', 'low', false, true, true, false, 'Use elemental zinc basis. Metallic taste and pectin/mineral interaction risk.'),
  ('Iron', '["Ferrous Fumarate","Ferrous Bisglycinate"]'::jsonb, 'Minerals', 5, 18, 'mg', 10, 'low', 'high', 'low', false, true, true, false, 'Metallic taste, oxidation, and child safety packaging review required.'),
  ('Sea Moss Extract 20:1', '["Sea Moss"]'::jsonb, 'Mineral / Wellness', 100, 500, 'mg', 250, 'medium', 'medium', 'medium', false, true, true, false, 'Mineral content and iodine variability require review.'),
  ('Vitamin D3', '["Cholecalciferol","Vitamin D"]'::jsonb, 'Vitamins', 400, 5000, 'IU', 1000, 'high', 'low', 'medium', true, false, true, false, 'IU values are not counted as mg load. Oil-soluble dispersion review recommended.'),
  ('Vitamin B12', '["Cyanocobalamin","Methylcobalamin"]'::jsonb, 'Vitamins', 100, 2500, 'mcg', 500, 'high', 'low', 'medium', false, false, false, false, 'Micro-dose vitamin. Verify form and overage.'),
  ('Vitamin B6', '["Pyridoxine"]'::jsonb, 'Vitamins', 1, 10, 'mg', 2, 'high', 'low', 'medium', false, false, false, false, 'Common B vitamin. Verify label claim and overage.'),
  ('Folate', '["Folic Acid","Methylfolate"]'::jsonb, 'Vitamins', 200, 1000, 'mcg', 400, 'high', 'low', 'medium', false, false, false, false, 'Micro-dose vitamin. Form and label units should be verified.'),
  ('Vitamin A', '["Retinyl Palmitate"]'::jsonb, 'Vitamins', 300, 1500, 'mcg', 900, 'medium', 'low', 'medium', true, false, true, false, 'Oil-soluble vitamin. Label units and upper limits require review.'),
  ('Vitamin E', '["Tocopherol","Mixed Tocopherols"]'::jsonb, 'Vitamins', 15, 100, 'mg', 15, 'medium', 'low', 'medium', true, false, true, false, 'Oil-soluble vitamin. Dispersion, label units, and upper limits require review.'),
  ('Cranberry Extract', '["Cranberry"]'::jsonb, 'Women''s Health', 250, 1000, 'mg', 500, 'medium', 'medium', 'medium', false, false, true, false, 'Tart taste. Verify PAC standardization if applicable.'),
  ('D-Mannose', '[]'::jsonb, 'Women''s Health', 500, 2000, 'mg', 1000, 'medium', 'low', 'low', false, false, true, false, 'High dose may require multiple gummies.'),
  ('Chasteberry Extract', '["Vitex","Vitex Agnus-Castus"]'::jsonb, 'Women''s Health', 20, 250, 'mg', 40, 'medium', 'medium', 'medium', false, false, true, false, 'Botanical and claim review recommended.'),
  ('Maca Root', '["Maca"]'::jsonb, 'Men''s Health / Energy', 500, 1500, 'mg', 500, 'medium', 'medium', 'medium', false, false, true, false, 'Earthy taste. Extract ratio should be verified.'),
  ('Saw Palmetto Extract', '["Saw Palmetto"]'::jsonb, 'Men''s Health', 160, 320, 'mg', 160, 'low', 'high', 'medium', true, false, true, false, 'Oil-rich botanical with strong taste. R&D review required.'),
  ('Tongkat Ali Extract', '["Tongkat Ali","Eurycoma Longifolia"]'::jsonb, 'Men''s Health', 100, 400, 'mg', 200, 'medium', 'high', 'medium', false, false, true, false, 'Bitter botanical. Regulatory and flavor review recommended.'),
  ('NMN', '[]'::jsonb, 'Healthy Aging / NAD Support', 125, 500, 'mg', 250, 'medium', 'medium', 'medium', false, false, true, false, 'Regulatory and stability review recommended.'),
  ('N-Acetyl Cysteine', '["NAC","NAC / N-Acetyl Cysteine"]'::jsonb, 'Antioxidant / Respiratory Support', 300, 600, 'mg', 300, 'low', 'high', 'medium', false, false, true, false, 'Strong sulfur odor/taste. Requires formulation review.'),
  ('CBD', '[]'::jsonb, 'Restricted Cannabinoid', 5, 50, 'mg', 10, 'restricted', 'high', 'medium', true, false, true, true, 'Restricted/high compliance risk. Not standard dietary supplement flow.'),
  ('D8 / Delta-8 THC', '["D8","Delta-8 THC"]'::jsonb, 'Restricted Cannabinoid', 2.5, 25, 'mg', 5, 'restricted', 'high', 'medium', true, false, true, true, 'Restricted/high compliance risk. Must not auto-approve.'),
  ('D9 / Delta-9 THC', '["D9","Delta-9 THC"]'::jsonb, 'Restricted Cannabinoid', 1, 10, 'mg', 2.5, 'restricted', 'high', 'medium', true, false, true, true, 'Restricted/high compliance risk. Must not auto-approve.'),
  ('CBD Full Spectrum', '[]'::jsonb, 'Restricted Cannabinoid', 5, 50, 'mg', 10, 'restricted', 'high', 'medium', true, false, true, true, 'May contain THC and other cannabinoids. Restricted/high compliance risk.')
on conflict (name) do update set
  aliases = excluded.aliases,
  category = excluded.category,
  common_dose_min = excluded.common_dose_min,
  common_dose_max = excluded.common_dose_max,
  unit = excluded.unit,
  default_dose = excluded.default_dose,
  gummy_suitability = excluded.gummy_suitability,
  taste_risk = excluded.taste_risk,
  heat_sensitivity = excluded.heat_sensitivity,
  oil_soluble = excluded.oil_soluble,
  mineral_heavy = excluded.mineral_heavy,
  requires_rd_review = excluded.requires_rd_review,
  regulatory_review_required = excluded.regulatory_review_required,
  notes = excluded.notes,
  updated_at = now();
