export type IngredientUnit = "mg" | "mcg" | "g" | "IU" | "billion CFU";

export type GummySuitability = "low" | "medium" | "high" | "restricted";

export type IngredientRisk = "low" | "medium" | "high";

export type ActiveIngredientDefinition = {
  name: string;
  aliases?: string[];
  category: string;
  common_dose_min: number;
  common_dose_max: number;
  unit: IngredientUnit;
  default_dose: number;
  bulk_price_usd_per_kg: number;
  gummy_suitability: GummySuitability;
  taste_risk: IngredientRisk;
  heat_sensitivity: IngredientRisk;
  oil_soluble: boolean;
  mineral_heavy: boolean;
  requires_rd_review: boolean;
  regulatory_review_required?: boolean;
  notes: string;
};

export const activeIngredients: ActiveIngredientDefinition[] = [
  {
    name: "Melatonin",
    category: "Sleep / Calm",
    common_dose_min: 1,
    common_dose_max: 10,
    unit: "mg",
    default_dose: 3,
    bulk_price_usd_per_kg: 80,
    gummy_suitability: "high",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Common sleep support active. Verify serving size and target market.",
  },
  {
    name: "L-Theanine",
    aliases: ["Theanine"],
    category: "Sleep / Calm",
    common_dose_min: 50,
    common_dose_max: 200,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 24,
    gummy_suitability: "high",
    taste_risk: "low",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Generally suitable for gummies. Mild taste profile.",
  },
  {
    name: "GABA",
    aliases: ["Gamma-Aminobutyric Acid"],
    category: "Sleep / Calm",
    common_dose_min: 50,
    common_dose_max: 250,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 8,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Bitter taste may require flavor masking at higher use levels.",
  },
  {
    name: "Chamomile Extract",
    aliases: ["Chamomile"],
    category: "Sleep / Calm",
    common_dose_min: 25,
    common_dose_max: 250,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Botanical extract ratio and allergen considerations should be reviewed.",
  },
  {
    name: "Lemon Balm Extract",
    aliases: ["Lemon Balm"],
    category: "Sleep / Calm",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 22,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Verify extract ratio and marker compounds if applicable.",
  },
  {
    name: "Passionflower Extract",
    aliases: ["Passionflower"],
    category: "Sleep / Calm",
    common_dose_min: 50,
    common_dose_max: 250,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 24,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Botanical taste may require flavor masking.",
  },
  {
    name: "Valerian Root Extract",
    aliases: ["Valerian Root", "Valerian"],
    category: "Sleep / Calm",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 28,
    gummy_suitability: "low",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Strong odor and taste. Requires formulation review.",
  },
  {
    name: "Magnesium L-Threonate",
    aliases: ["Magtein"],
    category: "Sleep / Calm",
    common_dose_min: 500,
    common_dose_max: 2000,
    unit: "mg",
    default_dose: 1000,
    bulk_price_usd_per_kg: 45,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: true,
    requires_rd_review: true,
    notes: "Use elemental magnesium basis where applicable. Mineral and pectin interaction review recommended.",
  },
  {
    name: "Ashwagandha Extract",
    aliases: ["Ashwagandha", "Withania Somnifera"],
    category: "Stress / Mood",
    common_dose_min: 125,
    common_dose_max: 600,
    unit: "mg",
    default_dose: 300,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Earthy taste and standardization should be reviewed.",
  },
  {
    name: "5-HTP",
    aliases: ["5-Hydroxytryptophan"],
    category: "Stress / Mood",
    common_dose_min: 25,
    common_dose_max: 100,
    unit: "mg",
    default_dose: 50,
    bulk_price_usd_per_kg: 60,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Regulatory, warning language, and stability review recommended.",
  },
  {
    name: "Rhodiola Rosea Extract",
    aliases: ["Rhodiola"],
    category: "Stress / Mood",
    common_dose_min: 100,
    common_dose_max: 400,
    unit: "mg",
    default_dose: 200,
    bulk_price_usd_per_kg: 85,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Verify rosavins and salidroside standardization.",
  },
  {
    name: "Saffron Extract",
    aliases: ["Saffron"],
    category: "Stress / Mood",
    common_dose_min: 15,
    common_dose_max: 30,
    unit: "mg",
    default_dose: 28,
    bulk_price_usd_per_kg: 1200,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Color and botanical standardization should be reviewed.",
  },
  {
    name: "Caffeine",
    aliases: ["Natural Caffeine"],
    category: "Energy / Focus",
    common_dose_min: 25,
    common_dose_max: 200,
    unit: "mg",
    default_dose: 50,
    bulk_price_usd_per_kg: 12,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Bitter active. Serving limits, warnings, and flavor masking required.",
  },
  {
    name: "L-Tyrosine",
    aliases: ["Tyrosine"],
    category: "Energy / Focus",
    common_dose_min: 500,
    common_dose_max: 2000,
    unit: "mg",
    default_dose: 500,
    bulk_price_usd_per_kg: 9,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Amino acid with moderate active load. Serving size and flavor impact should be reviewed.",
  },
  {
    name: "Green Tea Extract",
    aliases: ["EGCG", "Camellia Sinensis"],
    category: "Energy / Focus",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Bitter/astringent taste. EGCG and caffeine levels should be verified.",
  },
  {
    name: "Guarana Extract",
    aliases: ["Guarana"],
    category: "Energy / Focus",
    common_dose_min: 50,
    common_dose_max: 250,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 16,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Contains caffeine. Requires label and warning review.",
  },
  {
    name: "Ginseng Extract",
    aliases: ["Panax Ginseng", "Ginseng"],
    category: "Energy / Focus",
    common_dose_min: 100,
    common_dose_max: 400,
    unit: "mg",
    default_dose: 200,
    bulk_price_usd_per_kg: 65,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Botanical standardization and taste should be reviewed.",
  },
  {
    name: "Lion's Mane Mushroom",
    aliases: ["Lion's Mane", "Hericium Erinaceus"],
    category: "Nootropic",
    common_dose_min: 250,
    common_dose_max: 1000,
    unit: "mg",
    default_dose: 500,
    bulk_price_usd_per_kg: 35,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "High dose may require multiple gummies. Verify extract ratio.",
  },
  {
    name: "Alpha GPC",
    aliases: ["Alpha-GPC"],
    category: "Nootropic",
    common_dose_min: 100,
    common_dose_max: 600,
    unit: "mg",
    default_dose: 300,
    bulk_price_usd_per_kg: 80,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Hygroscopic behavior and taste should be evaluated.",
  },
  {
    name: "Citicoline",
    aliases: ["CDP Choline"],
    category: "Nootropic",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 95,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Review dose, taste, and regulatory positioning.",
  },
  {
    name: "Bacopa Monnieri Extract",
    aliases: ["Bacopa"],
    category: "Nootropic",
    common_dose_min: 150,
    common_dose_max: 450,
    unit: "mg",
    default_dose: 300,
    bulk_price_usd_per_kg: 45,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Bitter botanical. Verify bacoside standardization.",
  },
  {
    name: "Creatine Monohydrate",
    aliases: ["Creatine"],
    category: "Sports",
    common_dose_min: 1000,
    common_dose_max: 5000,
    unit: "mg",
    default_dose: 1000,
    bulk_price_usd_per_kg: 5,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "High-dose active. Serving size often needs multiple gummies.",
  },
  {
    name: "BCAA",
    aliases: ["Branched-Chain Amino Acids"],
    category: "Sports",
    common_dose_min: 1000,
    common_dose_max: 5000,
    unit: "mg",
    default_dose: 2000,
    bulk_price_usd_per_kg: 8,
    gummy_suitability: "low",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Very high dose and bitter taste. Technical review required.",
  },
  {
    name: "Beta-Alanine",
    category: "Sports",
    common_dose_min: 1600,
    common_dose_max: 3200,
    unit: "mg",
    default_dose: 1600,
    bulk_price_usd_per_kg: 7,
    gummy_suitability: "low",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "High-dose sports active. Serving size will likely require multiple gummies.",
  },
  {
    name: "Citrulline Malate",
    aliases: ["L-Citrulline"],
    category: "Sports",
    common_dose_min: 1000,
    common_dose_max: 6000,
    unit: "mg",
    default_dose: 1000,
    bulk_price_usd_per_kg: 8,
    gummy_suitability: "low",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Very high active load for gummies. Technical review and multi-gummy serving likely required.",
  },
  {
    name: "L-Carnitine",
    aliases: ["Carnitine"],
    category: "Sports",
    common_dose_min: 250,
    common_dose_max: 1500,
    unit: "mg",
    default_dose: 500,
    bulk_price_usd_per_kg: 12,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Dose and taste may require flavor masking.",
  },
  {
    name: "Electrolyte Blend",
    aliases: ["Electrolytes"],
    category: "Sports",
    common_dose_min: 100,
    common_dose_max: 1000,
    unit: "mg",
    default_dose: 300,
    bulk_price_usd_per_kg: 4,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: true,
    requires_rd_review: true,
    notes: "Mineral salts may affect taste, pectin, and texture.",
  },
  {
    name: "Collagen Peptides",
    aliases: ["Collagen"],
    category: "Beauty",
    common_dose_min: 500,
    common_dose_max: 5000,
    unit: "mg",
    default_dose: 1000,
    bulk_price_usd_per_kg: 8,
    gummy_suitability: "low",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "High dose active. May require multiple gummies or alternate format.",
  },
  {
    name: "Hyaluronic Acid",
    aliases: ["Sodium Hyaluronate"],
    category: "Beauty",
    common_dose_min: 50,
    common_dose_max: 200,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 160,
    gummy_suitability: "medium",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Review molecular weight and supplier specification.",
  },
  {
    name: "Biotin",
    aliases: ["Vitamin B7"],
    category: "Beauty",
    common_dose_min: 30,
    common_dose_max: 5000,
    unit: "mcg",
    default_dose: 2500,
    bulk_price_usd_per_kg: 180,
    gummy_suitability: "high",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Micro-dose vitamin. Verify label claim and overage.",
  },
  {
    name: "Keratin",
    category: "Beauty",
    common_dose_min: 250,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Protein-derived active. Source, allergen status, and taste should be reviewed.",
  },
  {
    name: "Bamboo Extract",
    aliases: ["Bambusa Vulgaris", "Bambusa Vulgaris / Bamboo Extract"],
    category: "Beauty / Joint / Mineral Support",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 16,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Often standardized for silica. Verify extract ratio and silica content.",
  },
  {
    name: "Lutein",
    category: "Eye Health",
    common_dose_min: 5,
    common_dose_max: 20,
    unit: "mg",
    default_dose: 10,
    bulk_price_usd_per_kg: 220,
    gummy_suitability: "medium",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Oil-soluble carotenoid. May require dispersion system.",
  },
  {
    name: "Zeaxanthin",
    category: "Eye Health",
    common_dose_min: 1,
    common_dose_max: 10,
    unit: "mg",
    default_dose: 2,
    bulk_price_usd_per_kg: 650,
    gummy_suitability: "medium",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Oil-soluble carotenoid. Review dispersion and color impact.",
  },
  {
    name: "Beta Carotene",
    category: "Vitamin / Eye Health",
    common_dose_min: 1,
    common_dose_max: 6,
    unit: "mg",
    default_dose: 3,
    bulk_price_usd_per_kg: 95,
    gummy_suitability: "medium",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Oil-soluble carotenoid. May require dispersion system.",
  },
  {
    name: "Vitamin C",
    aliases: ["Ascorbic Acid"],
    category: "Immune",
    common_dose_min: 60,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 4,
    gummy_suitability: "high",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Acidic taste can support fruit profiles but may affect pH.",
  },
  {
    name: "Elderberry Extract",
    aliases: ["Elderberry"],
    category: "Immune",
    common_dose_min: 50,
    common_dose_max: 300,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 22,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Can contribute dark color and berry flavor notes.",
  },
  {
    name: "Echinacea Extract",
    aliases: ["Echinacea"],
    category: "Immune",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 20,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Botanical extract ratio and taste should be reviewed.",
  },
  {
    name: "Quercetin",
    category: "Immune",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 45,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Bitter and colored active. May need flavor masking.",
  },
  {
    name: "Probiotics",
    aliases: ["Probiotic"],
    category: "Digestive",
    common_dose_min: 1,
    common_dose_max: 10,
    unit: "billion CFU",
    default_dose: 2,
    bulk_price_usd_per_kg: 180,
    gummy_suitability: "low",
    taste_risk: "low",
    heat_sensitivity: "high",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "CFU should not be counted as mg active load. Heat stability and overage required.",
  },
  {
    name: "Prebiotic Fiber",
    aliases: ["Inulin", "FOS", "Fructooligosaccharides"],
    category: "Digestive",
    common_dose_min: 500,
    common_dose_max: 3000,
    unit: "mg",
    default_dose: 1000,
    bulk_price_usd_per_kg: 3,
    gummy_suitability: "medium",
    taste_risk: "low",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "High dose can affect texture and water activity.",
  },
  {
    name: "Apple Cider Vinegar",
    aliases: ["ACV"],
    category: "Digestive",
    common_dose_min: 250,
    common_dose_max: 1000,
    unit: "mg",
    default_dose: 500,
    bulk_price_usd_per_kg: 8,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Strong acidic taste and odor. Requires flavor review.",
  },
  {
    name: "Ginger Root Extract",
    aliases: ["Ginger"],
    category: "Digestive",
    common_dose_min: 50,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 14,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Spicy taste can be useful in some flavor systems.",
  },
  {
    name: "Peppermint Leaf Extract",
    aliases: ["Peppermint"],
    category: "Digestive",
    common_dose_min: 50,
    common_dose_max: 250,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Botanical extract with strong flavor contribution. Verify extract ratio.",
  },
  {
    name: "CoQ10",
    aliases: ["Coenzyme Q10", "Ubiquinone"],
    category: "Heart / Metabolic",
    common_dose_min: 30,
    common_dose_max: 200,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 250,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Oil-soluble active. Dispersion and color should be reviewed.",
  },
  {
    name: "Algae-based Omega-3 DHA",
    aliases: ["DHA", "Algae DHA", "Omega-3 DHA"],
    category: "Heart / Brain / Eye Health",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 75,
    gummy_suitability: "low",
    taste_risk: "high",
    heat_sensitivity: "high",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Oil-soluble, oxidation and off-taste risk. May need emulsification.",
  },
  {
    name: "Berberine",
    category: "Heart / Metabolic",
    common_dose_min: 250,
    common_dose_max: 1000,
    unit: "mg",
    default_dose: 500,
    bulk_price_usd_per_kg: 55,
    gummy_suitability: "low",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Very bitter active and high dose. Technical review required.",
  },
  {
    name: "Chromium Picolinate",
    aliases: ["Chromium"],
    category: "Heart / Metabolic",
    common_dose_min: 35,
    common_dose_max: 200,
    unit: "mcg",
    default_dose: 120,
    bulk_price_usd_per_kg: 60,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: true,
    requires_rd_review: true,
    notes: "Use elemental chromium basis. Mineral review recommended.",
  },
  {
    name: "Resveratrol",
    category: "Heart / Metabolic",
    common_dose_min: 50,
    common_dose_max: 250,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 110,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Botanical polyphenol. Color, taste, and stability review recommended.",
  },
  {
    name: "Turmeric Root Extract 4:1",
    aliases: ["Turmeric", "Curcumin"],
    category: "Joint / Inflammation Support",
    common_dose_min: 250,
    common_dose_max: 1000,
    unit: "mg",
    default_dose: 500,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Strong taste/color. Verify curcuminoid standardization if applicable.",
  },
  {
    name: "Glucosamine Sulfate",
    aliases: ["Glucosamine"],
    category: "Joint",
    common_dose_min: 500,
    common_dose_max: 1500,
    unit: "mg",
    default_dose: 750,
    bulk_price_usd_per_kg: 8,
    gummy_suitability: "low",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "High dose and potential shellfish allergen review required.",
  },
  {
    name: "Chondroitin Sulfate",
    aliases: ["Chondroitin"],
    category: "Joint",
    common_dose_min: 400,
    common_dose_max: 1200,
    unit: "mg",
    default_dose: 400,
    bulk_price_usd_per_kg: 28,
    gummy_suitability: "low",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "High dose and animal source documentation should be reviewed.",
  },
  {
    name: "MSM",
    aliases: ["Methylsulfonylmethane"],
    category: "Joint",
    common_dose_min: 500,
    common_dose_max: 2000,
    unit: "mg",
    default_dose: 1000,
    bulk_price_usd_per_kg: 5,
    gummy_suitability: "low",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Sulfur taste and high load require formulation review.",
  },
  {
    name: "Calcium",
    aliases: ["Calcium Citrate", "Calcium Carbonate"],
    category: "Minerals",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 3,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: true,
    requires_rd_review: true,
    notes: "Use elemental calcium basis. Pectin interaction risk.",
  },
  {
    name: "Magnesium Glycinate",
    aliases: ["Magnesium"],
    category: "Minerals",
    common_dose_min: 50,
    common_dose_max: 200,
    unit: "mg",
    default_dose: 100,
    bulk_price_usd_per_kg: 7,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: true,
    requires_rd_review: true,
    notes: "Use elemental magnesium basis. Mineral/pectin interaction risk.",
  },
  {
    name: "Zinc Citrate",
    aliases: ["Zinc"],
    category: "Mineral / Immune",
    common_dose_min: 5,
    common_dose_max: 15,
    unit: "mg",
    default_dose: 10,
    bulk_price_usd_per_kg: 8,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: true,
    requires_rd_review: true,
    notes: "Use elemental zinc basis. Metallic taste and pectin/mineral interaction risk.",
  },
  {
    name: "Iron",
    aliases: ["Ferrous Fumarate", "Ferrous Bisglycinate"],
    category: "Minerals",
    common_dose_min: 5,
    common_dose_max: 18,
    unit: "mg",
    default_dose: 10,
    bulk_price_usd_per_kg: 5,
    gummy_suitability: "low",
    taste_risk: "high",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: true,
    requires_rd_review: true,
    notes: "Metallic taste, oxidation, and child safety packaging review required.",
  },
  {
    name: "Sea Moss Extract 20:1",
    aliases: ["Sea Moss"],
    category: "Mineral / Wellness",
    common_dose_min: 100,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: true,
    requires_rd_review: true,
    notes: "Mineral content and iodine variability require review.",
  },
  {
    name: "Vitamin D3",
    aliases: ["Cholecalciferol", "Vitamin D"],
    category: "Vitamins",
    common_dose_min: 400,
    common_dose_max: 5000,
    unit: "IU",
    default_dose: 1000,
    bulk_price_usd_per_kg: 350,
    gummy_suitability: "high",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "IU values are not counted as mg load. Oil-soluble dispersion review recommended.",
  },
  {
    name: "Vitamin B12",
    aliases: ["Cyanocobalamin", "Methylcobalamin"],
    category: "Vitamins",
    common_dose_min: 100,
    common_dose_max: 2500,
    unit: "mcg",
    default_dose: 500,
    bulk_price_usd_per_kg: 1800,
    gummy_suitability: "high",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Micro-dose vitamin. Verify form and overage.",
  },
  {
    name: "Vitamin B6",
    aliases: ["Pyridoxine"],
    category: "Vitamins",
    common_dose_min: 1,
    common_dose_max: 10,
    unit: "mg",
    default_dose: 2,
    bulk_price_usd_per_kg: 35,
    gummy_suitability: "high",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Common B vitamin. Verify label claim and overage.",
  },
  {
    name: "Folate",
    aliases: ["Folic Acid", "Methylfolate"],
    category: "Vitamins",
    common_dose_min: 200,
    common_dose_max: 1000,
    unit: "mcg",
    default_dose: 400,
    bulk_price_usd_per_kg: 600,
    gummy_suitability: "high",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: false,
    notes: "Micro-dose vitamin. Form and label units should be verified.",
  },
  {
    name: "Vitamin A",
    aliases: ["Retinyl Palmitate"],
    category: "Vitamins",
    common_dose_min: 300,
    common_dose_max: 1500,
    unit: "mcg",
    default_dose: 900,
    bulk_price_usd_per_kg: 220,
    gummy_suitability: "medium",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Oil-soluble vitamin. Label units and upper limits require review.",
  },
  {
    name: "Vitamin E",
    aliases: ["Tocopherol", "Mixed Tocopherols"],
    category: "Vitamins",
    common_dose_min: 15,
    common_dose_max: 100,
    unit: "mg",
    default_dose: 15,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "low",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Oil-soluble vitamin. Dispersion, label units, and upper limits require review.",
  },
  {
    name: "Cranberry Extract",
    aliases: ["Cranberry"],
    category: "Women's Health",
    common_dose_min: 250,
    common_dose_max: 1000,
    unit: "mg",
    default_dose: 500,
    bulk_price_usd_per_kg: 25,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Tart taste. Verify PAC standardization if applicable.",
  },
  {
    name: "D-Mannose",
    category: "Women's Health",
    common_dose_min: 500,
    common_dose_max: 2000,
    unit: "mg",
    default_dose: 1000,
    bulk_price_usd_per_kg: 18,
    gummy_suitability: "medium",
    taste_risk: "low",
    heat_sensitivity: "low",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "High dose may require multiple gummies.",
  },
  {
    name: "Chasteberry Extract",
    aliases: ["Vitex", "Vitex Agnus-Castus"],
    category: "Women's Health",
    common_dose_min: 20,
    common_dose_max: 250,
    unit: "mg",
    default_dose: 40,
    bulk_price_usd_per_kg: 28,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Botanical and claim review recommended.",
  },
  {
    name: "Maca Root",
    aliases: ["Maca"],
    category: "Men's Health / Energy",
    common_dose_min: 500,
    common_dose_max: 1500,
    unit: "mg",
    default_dose: 500,
    bulk_price_usd_per_kg: 12,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Earthy taste. Extract ratio should be verified.",
  },
  {
    name: "Saw Palmetto Extract",
    aliases: ["Saw Palmetto"],
    category: "Men's Health",
    common_dose_min: 160,
    common_dose_max: 320,
    unit: "mg",
    default_dose: 160,
    bulk_price_usd_per_kg: 45,
    gummy_suitability: "low",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Oil-rich botanical with strong taste. R&D review required.",
  },
  {
    name: "Tongkat Ali Extract",
    aliases: ["Tongkat Ali", "Eurycoma Longifolia"],
    category: "Men's Health",
    common_dose_min: 100,
    common_dose_max: 400,
    unit: "mg",
    default_dose: 200,
    bulk_price_usd_per_kg: 75,
    gummy_suitability: "medium",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Bitter botanical. Regulatory and flavor review recommended.",
  },
  {
    name: "NMN",
    category: "Healthy Aging / NAD Support",
    common_dose_min: 125,
    common_dose_max: 500,
    unit: "mg",
    default_dose: 250,
    bulk_price_usd_per_kg: 300,
    gummy_suitability: "medium",
    taste_risk: "medium",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Regulatory and stability review recommended.",
  },
  {
    name: "N-Acetyl Cysteine",
    aliases: ["NAC", "NAC / N-Acetyl Cysteine"],
    category: "Antioxidant / Respiratory Support",
    common_dose_min: 300,
    common_dose_max: 600,
    unit: "mg",
    default_dose: 300,
    bulk_price_usd_per_kg: 12,
    gummy_suitability: "low",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: false,
    mineral_heavy: false,
    requires_rd_review: true,
    notes: "Strong sulfur odor/taste. Requires formulation review.",
  },
  {
    name: "CBD",
    category: "Restricted Cannabinoid",
    common_dose_min: 5,
    common_dose_max: 50,
    unit: "mg",
    default_dose: 10,
    bulk_price_usd_per_kg: 900,
    gummy_suitability: "restricted",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    regulatory_review_required: true,
    notes: "Restricted/high compliance risk. Not standard dietary supplement flow.",
  },
  {
    name: "D8 / Delta-8 THC",
    aliases: ["D8", "Delta-8 THC"],
    category: "Restricted Cannabinoid",
    common_dose_min: 2.5,
    common_dose_max: 25,
    unit: "mg",
    default_dose: 5,
    bulk_price_usd_per_kg: 600,
    gummy_suitability: "restricted",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    regulatory_review_required: true,
    notes: "Restricted/high compliance risk. Must not auto-approve.",
  },
  {
    name: "D9 / Delta-9 THC",
    aliases: ["D9", "Delta-9 THC"],
    category: "Restricted Cannabinoid",
    common_dose_min: 1,
    common_dose_max: 10,
    unit: "mg",
    default_dose: 2.5,
    bulk_price_usd_per_kg: 1200,
    gummy_suitability: "restricted",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    regulatory_review_required: true,
    notes: "Restricted/high compliance risk. Must not auto-approve.",
  },
  {
    name: "CBD Full Spectrum",
    category: "Restricted Cannabinoid",
    common_dose_min: 5,
    common_dose_max: 50,
    unit: "mg",
    default_dose: 10,
    bulk_price_usd_per_kg: 900,
    gummy_suitability: "restricted",
    taste_risk: "high",
    heat_sensitivity: "medium",
    oil_soluble: true,
    mineral_heavy: false,
    requires_rd_review: true,
    regulatory_review_required: true,
    notes: "May contain THC and other cannabinoids. Restricted/high compliance risk.",
  },
];

function normalizeIngredientName(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^\w\s-]/g, " ")
    .replace(/\s+/g, " ");
}

const ingredientLookup = new Map<string, ActiveIngredientDefinition>();

activeIngredients.forEach((ingredient) => {
  ingredientLookup.set(normalizeIngredientName(ingredient.name), ingredient);
  ingredient.aliases?.forEach((alias) => {
    ingredientLookup.set(normalizeIngredientName(alias), ingredient);
  });
});

export const uniqueActiveIngredients = Array.from(
  new Map(
    activeIngredients.map((ingredient) => [
      normalizeIngredientName(ingredient.name),
      ingredient,
    ]),
  ).values(),
);

export function findActiveIngredient(value: string) {
  return ingredientLookup.get(normalizeIngredientName(value)) ?? null;
}

export function searchActiveIngredients(query: string) {
  const normalizedQuery = normalizeIngredientName(query);

  if (!normalizedQuery) {
    return uniqueActiveIngredients;
  }

  return uniqueActiveIngredients.filter((ingredient) => {
    const searchableValues = [
      ingredient.name,
      ingredient.category,
      ...(ingredient.aliases ?? []),
    ].map(normalizeIngredientName);

    return searchableValues.some((value) => value.includes(normalizedQuery));
  });
}
